version: '3.6'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3308:3306"
    volumes:
      - ./my_data:/var/lib/mysql

  web:
    image: ebspace/aarch64-apache-php
    ports:
      - "8080:80"
    links:
      - db
    volumes:
      - ./:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306